force-app/main/default/objects/student__c/student__c.object-meta.xml
<CustomObject>
    <description>This is student object. Test description</description>
    <label>Student</label>
    <nameField>
        <displayFormat>st-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/student__c/fields/Linked_User__c.field-meta.xml
<CustomField>
    <fullName>Linked_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>linkedusers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/student__c/fields/Student_Email__c.field-meta.xml
<CustomField>
    <fullName>Student_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This is student email descriptiomn</description>
    <externalId>true</externalId>
    <inlineHelpText>Enter your email</inlineHelpText>
    <label>Student Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/student__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <description>This is student name description</description>
    <inlineHelpText>Enter you name</inlineHelpText>
    <label>Student Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomSelfRegHandler.cls
public without sharing class CustomSelfRegHandler {

    @AuraEnabled
    public static String selfRegister(String firstName, String lastName, String email, String studentName, String password) {

        
        try {
            
        Contact contact = new Contact(FirstName = firstName, LastName = lastName);
        insert contact;

        // Create User record
        User newUser = new User();
        newUser.FirstName = firstName;
        newUser.LastName = lastName;
        newUser.Email = email;
        newUser.Username = email; // Ensure username is unique
        newUser.Alias = firstName.substring(0, 1) + lastName.substring(0, 1);
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.LocaleSidKey = 'en_US';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.LanguageLocaleKey = 'en_US';
        newUser.ContactId = contact.Id;
        newUser.ProfileId = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus User' LIMIT 1].Id;
 
        // Insert User record
        insert newUser;
        System.debug('User created for experience cloud');

        // set password
        System.setPassword(newUser.Id, password);
 
        // Create Student record
        Student__c newStudent = new Student__c();
        newStudent.Student_Name__c = studentName;
        newStudent.Student_Email__c = email;
        newStudent.Linked_User__c = newUser.Id; // Link User to Student
        insert newStudent;
        System.debug('Student created for experience cloud');
 
        return 'Registration successful';
        } catch (Exception e) {
            return 'error' + e.getMessage();
        }
    }
}